### ISSUE TITLE
Version update policy

### ISSUE THREAD

**Issue by bow** [conda-forge/jinja2-feedstock#7]
Dear jinja2-feedstock maintainers,

There has been [a slew of updates](http://jinja.pocoo.org/docs/2.9/changelog/) for the Jinja2 package since the version used in this feedstock (2.8) was released about 6 months ago.

I was wondering, what is the update policy of this particular feedstock? Should all point releases be built for conda-forge or only the major releases? Are there any plans on   updating the recipes so that the latest Jinja2 can be included in conda-forge?

Thanks in advance!

**Comment by ocefpaf** [comment]
> I was wondering, what is the update policy of this particular feedstock?

There is no policy per-se. But what happens may depend on the maintainers time.

> Should all point releases be built for conda-forge or only the major releases?

If a maintainer wants to provide all point releases sure. But that is quite time consuming.

> Are there any plans on updating the recipes so that the latest Jinja2 can be included in conda-forge?

The beauty of conda-forge is that you don't need to wait for the maintainers to do so. You can send a PR updating it yourself and, once it is merged, the package will be uploaded to the channel.

Are you interested in send that PR? Also, Are you interested in becoming a maintainer?

**Comment by bow** [comment]
I finally have time to look at the setup and yes, I am interested in sending a PR. I have a [local branch](https://github.com/bow/jinja2-feedstock/tree/version-2.9.5) on which I am testing the changes on [all](https://circleci.com/gh/bow/jinja2-feedstock/2) [the CI](https://ci.appveyor.com/project/bow/jinja2-feedstock) [platforms](https://travis-ci.org/bow/jinja2-feedstock/builds/202063353). Let's see how they go first.

On related note, it seems that different versions of a feedstock can not be present on a single repo branch. Is this really the case or am I missing something?

**Comment by jakirkham** [comment]
Going to close as the question is answered and a version update PR ( https://github.com/conda-forge/jinja2-feedstock/pull/8 ) has been issued.
